### ISSUE TITLE
need help:what's the meaning of auth loginc?

### ISSUE THREAD

**Issue by kaixinbuyu** [BlueprintProject/GridWorker#1]
1.when worker client connect to websocket server,invoke: go c.announceAuth();

2.then the server received the client auth regist message:
// handleAuthMessageForConnection handles actual auth commands
func (d *DistributedWorker) handleAuthMessageForConnection(m *Message, c *connection) {
	id := m.GetString("id")
	r := d.remoteWorkerRegistry[id]

	if r == nil {
		r = d.newRemoteWorker()
		d.remoteWorkerRegistry[id] = r
	}

	r.connectionQueue <- c
	c.remoteWorker = r

	c.announceAuth()  // 3.why server invoke auth again?

	go func(d *DistributedWorker, r *remoteWorker) {
		time.Sleep(1 * time.Second)  // 4.and what does this mean?
		d.remoteWorkerQueue <- r 
	}(d, r)
}

**Comment by Hunter-Dolan** [comment]
The auth logic is more of an identification handshake at this point. The process is setup to allow some form of authentication (shared key, cert signing, etc), however it was never fully coded as the network that the peers connect across is assumed to be secure.

This may be a false assumption for some types of infrastructures, but then again, it probably wouldn't be wise to run this on anything other than a secured network.

So with that in mind, and the fact that this is a multi node system.

The secondary "announceAuth" is triggered to give the peers response to the authentication request.

You can think of a transactions like this:

```
Node A: Connect to Node B @ 10.0.0.2
Node B: Accept Connection
Node B: Identify self as Node B (IE: "announceAuth")
Node A: Receive Authentication Announcement. Add node to register.
Node A: Annouce Auth (so that node B can identify node A)
Node B: Receive Authentication Announcement. Add node to register.
```

AnnouceAuth can only be fired once per node connection so this does not repeat in an endless loop. 

The reason for the delay in adding to node to the remoteWorkerQueue is that, due to the async nature of this project, and go, occasionally on a fast connection a worker could be added to the queue before the inverse peer could finish initializing.

This could probably be done better by having an additional handshake to confirm the finalization of initializing. But considering this only impacts initial connection, it wasn't worth writing the additional logic for the application I am using this for.

Pull Requests are welcome to improve any of the above.

- Hunter
